

INSERT INTO especialidades VALUES (1, 'ESPECIALIDAD 1');
INSERT INTO especialidades VALUES (2, 'ESPECIALIDAD 2');
INSERT INTO especialidades VALUES (4, 'Medicina');
INSERT INTO especialidades VALUES (5, 'Ginecobstetricia');
INSERT INTO especialidades VALUES (6, 'Pediatría');
INSERT INTO especialidades VALUES (7, 'Odontología');
INSERT INTO especialidades VALUES (8, 'Servicios de Diagnóstico y Apoyo');
INSERT INTO especialidades VALUES (9, 'Otras Atenciones Consulta Externa Médica');
INSERT INTO especialidades VALUES (10, 'Medicina General');
INSERT INTO especialidades VALUES (11, 'Medicina Interna');
INSERT INTO especialidades VALUES (12, 'Dermatología');
INSERT INTO especialidades VALUES (13, 'Endocrinología');
INSERT INTO especialidades VALUES (14, 'Nefrología');
INSERT INTO especialidades VALUES (15, 'Neurología');
INSERT INTO especialidades VALUES (16, 'Cardiología');
INSERT INTO especialidades VALUES (17, 'Neumología');
INSERT INTO especialidades VALUES (18, 'Gastroenterología');
INSERT INTO especialidades VALUES (19, 'Hematología');
INSERT INTO especialidades VALUES (20, 'Oncología');
INSERT INTO especialidades VALUES (21, 'Reumatología');
INSERT INTO especialidades VALUES (22, 'Nutriología');
INSERT INTO especialidades VALUES (23, 'CENid');
INSERT INTO especialidades VALUES (24, 'Psiquiatría');
INSERT INTO especialidades VALUES (25, 'Anestesiología');
INSERT INTO especialidades VALUES (26, 'Ortopedia');
INSERT INTO especialidades VALUES (27, 'Neurocirugía');
INSERT INTO especialidades VALUES (28, 'Oftalmología');
INSERT INTO especialidades VALUES (29, 'Otorrinolaringología');
INSERT INTO especialidades VALUES (30, 'Urología');
INSERT INTO especialidades VALUES (31, 'Cirugía Plástica');
INSERT INTO especialidades VALUES (32, 'Proctología');
INSERT INTO especialidades VALUES (33, 'Cirugía de Tórax');
INSERT INTO especialidades VALUES (34, 'Cirugía Maxilofacial');
INSERT INTO especialidades VALUES (35, 'Cirugía Cardiovascular');
INSERT INTO especialidades VALUES (36, 'Cirugía Oncológica');
INSERT INTO especialidades VALUES (37, 'Ginecología');
INSERT INTO especialidades VALUES (38, 'Clínica de Mamas');
INSERT INTO especialidades VALUES (39, 'Infertilidad');
INSERT INTO especialidades VALUES (40, 'Uroginecología');
INSERT INTO especialidades VALUES (41, 'Cirugía Ginecológica');
INSERT INTO especialidades VALUES (42, 'Emergencia Ginecológica');
INSERT INTO especialidades VALUES (43, 'Detección de Embarazo de Alto Riesgo');
INSERT INTO especialidades VALUES (44, 'Embarazo de Alto Riesgo');
INSERT INTO especialidades VALUES (45, 'Perinatología');
INSERT INTO especialidades VALUES (46, 'Puerperio');
INSERT INTO especialidades VALUES (47, 'Cirugía Obstetricia');
INSERT INTO especialidades VALUES (48, 'Emergencia Obstétrica');
INSERT INTO especialidades VALUES (49, 'Neonatología');
INSERT INTO especialidades VALUES (50, 'Medicina Pediátrica');
INSERT INTO especialidades VALUES (51, 'Cirugía Pediátrica');
INSERT INTO especialidades VALUES (52, 'Cirugía Neonatal');
INSERT INTO especialidades VALUES (53, 'Pediatría General');
INSERT INTO especialidades VALUES (54, 'Neurología Pediátrica');
INSERT INTO especialidades VALUES (55, 'Cardiología Pediátrica');
INSERT INTO especialidades VALUES (56, 'Neumología Pediátrica');
INSERT INTO especialidades VALUES (57, 'Dermatología Pediátrica');
INSERT INTO especialidades VALUES (58, 'Hematología pediátrica');
INSERT INTO especialidades VALUES (59, 'Urología pediátrica');
INSERT INTO especialidades VALUES (60, 'Nefrología pediátrica');
INSERT INTO especialidades VALUES (61, 'Endocrinología Pediátrica');
INSERT INTO especialidades VALUES (62, 'Fisiatria Pediátrica');
INSERT INTO especialidades VALUES (63, 'Gastroenterología Pediátrica');
INSERT INTO especialidades VALUES (64, 'Nutriología Pediátrica');
INSERT INTO especialidades VALUES (65, 'Reumatología Pediátrica');
INSERT INTO especialidades VALUES (66, 'Cirugía Plástica Pediátrica');
INSERT INTO especialidades VALUES (67, 'Cirugía Cardiovascular Pediátrica');
INSERT INTO especialidades VALUES (68, 'Cirugía Maxilofacial Pediátrica');
INSERT INTO especialidades VALUES (69, 'Cirugía Oncológica Pediátrica');
INSERT INTO especialidades VALUES (70, 'Neurocirugía Pediátrica');
INSERT INTO especialidades VALUES (71, 'Oftalmología Pediátrica');
INSERT INTO especialidades VALUES (72, 'Oncología Pediátrica');
INSERT INTO especialidades VALUES (73, 'Ortopedia Pediátrica');
INSERT INTO especialidades VALUES (74, 'Otorrinolaringología Pediátrica');
INSERT INTO especialidades VALUES (75, 'Cirugía Oral');
INSERT INTO especialidades VALUES (76, 'Medicina Nuclear');
INSERT INTO especialidades VALUES (77, 'Patología');
INSERT INTO especialidades VALUES (78, 'Medicina Física');
INSERT INTO especialidades VALUES (79, 'Fisiatría');
INSERT INTO especialidades VALUES (80, 'Genética');
INSERT INTO especialidades VALUES (81, 'Banco sangre');
INSERT INTO especialidades VALUES (82, 'Banco de leche');
INSERT INTO especialidades VALUES (83, 'Clínica de Ulceras');
INSERT INTO especialidades VALUES (84, 'Medicina Familiar');
INSERT INTO especialidades VALUES (85, 'Nutrición');
INSERT INTO especialidades VALUES (86, 'Programa de Atención Integral');
INSERT INTO especialidades VALUES (87, 'Psicología');
INSERT INTO especialidades VALUES (88, 'Selección');
INSERT INTO especialidades VALUES (89, 'Unidades del dolor y cuidados paliativos');
INSERT INTO especialidades VALUES (90, 'Laboratorio Clínico');
INSERT INTO especialidades VALUES (91, 'Imagenología');
INSERT INTO especialidades VALUES (92, 'Referido Externo');
INSERT INTO especialidades VALUES (93, 'Farmacia');
INSERT INTO especialidades VALUES (94, 'Cirugía Vascular');
INSERT INTO especialidades VALUES (95, 'Traumatología-Ortopedica');
INSERT INTO especialidades VALUES (96, 'Colposcopía');
INSERT INTO especialidades VALUES (97, 'Endoscopía');
INSERT INTO especialidades VALUES (98, 'Infectología');
INSERT INTO especialidades VALUES (99, 'Obstetricia');
INSERT INTO especialidades VALUES (100, 'Alergología');
INSERT INTO especialidades VALUES (101, 'Cirugía Endoscópica');
INSERT INTO especialidades VALUES (102, 'Clínica de cesación de consumo de tabaco');
INSERT INTO especialidades VALUES (103, 'Atención Materno Infantil');
INSERT INTO especialidades VALUES (104, 'Cirugía');
INSERT INTO especialidades VALUES (105, 'Cirugía General');
INSERT INTO especialidades VALUES (106, 'Planificación Familiar');
INSERT INTO especialidades VALUES (107, 'Adolescencia');
INSERT INTO especialidades VALUES (108, 'Clínica VICITS');
INSERT INTO especialidades VALUES (109, 'Clínica TAR');
INSERT INTO especialidades VALUES (110, 'Programa VIH');
INSERT INTO especialidades VALUES (111, 'Programa Nacional de Tuberculosis y Enfermedades Respiratorias');
INSERT INTO especialidades VALUES (112, 'Adulto Mayor');
INSERT INTO especialidades VALUES (113, 'Infectología Pediátrica');
INSERT INTO especialidades VALUES (114, 'Alergología pediátrica');
